# Generated by Django 2.2.1 on 2019-09-10 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('pic', models.ImageField(default='pr.png', upload_to='profile')),
                ('status', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Signup')),
            ],
        ),
    ]
